name: fuzzer workflow 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runscript:
    name: Build and run docker container
    runs-on: ubuntu-latest
    steps:
      - uses actions/checkout@v2

      - name: Run build
        run: |
          chmod +x ${GITHUB_WORKSPACE}/build.sh
          ${GITHUB_WORKSPACE}/build.sh
        shell: bash


        - name: Run Docker container
          run: |
            chmod +x ${GITHUB_WORKSPACE}/run.sh
            ${GITHUB_WORKSPACE}/run.sh
